### ISSUE TITLE
Problem running the example from Usage section

### ISSUE THREAD

**Issue by ssuukk** [suno-ai/bark#178]
After installing bark and trying to run the code from Usage, I'm  getting this:

```
(deeplearning) PS D:\Projekty\bark_test> python .\bark.py
Traceback (most recent call last):
  File ".\bark.py", line 1, in <module>
    from bark import generate_audio, preload_models
  File "D:\Projekty\bark_test\bark.py", line 1, in <module>
    from bark import generate_audio, preload_models
ImportError: cannot import name 'generate_audio' from partially initialized module 'bark' (most likely due to a circular import) (D:\Projekty\bark_test\bark.py)
```

**Comment by gkucsko** [comment]
hm, are you sure you have the correct bark installed? install either directly from github or clone the repo. don't use pypi

**Comment by mcamac** [comment]
Try renaming your script from bark.py to something like bark_example.py. Looks like it's trying to import from itself instead of the bark package.
