### ISSUE TITLE
Invalid Syntax? 

### ISSUE THREAD

**Issue by murvinlai** [suno-ai/bark#199]
I keep getting this error:
Traceback (most recent call last):
  File "test-1.py", line 2, in <module>
    from bark import SAMPLE_RATE, generate_audio, preload_models
  File "/Users/murvinlai/Documents/Projects/Text2Speech/bark/bark/__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform, save_as_prompt
  File "/Users/murvinlai/Documents/Projects/Text2Speech/bark/bark/api.py", line 9
    text: str,
        ^
SyntaxError: invalid syntax

And I just copy your code:

# -*- coding: utf-8 -*-
from bark import SAMPLE_RATE, generate_audio, preload_models
from IPython.display import Audio

# download and load all models
preload_models()

# generate audio from text
text_prompt = """
     Hello, my name is Suno. And, uh — and I like pizza. [laughs]
     But I also have other interests such as playing tic tac toe.
"""

audio_array = generate_audio(text_prompt)

# play text in notebook
Audio(audio_array, rate=SAMPLE_RATE)

**Comment by murvinlai** [comment]
I tried running on Python3.. now i get:


Traceback (most recent call last):
  File "/Users/murvinlai/Documents/Projects/Text2Speech/bark/test-1.py", line 2, in <module>
    from bark import SAMPLE_RATE, generate_audio, preload_models
  File "/Users/murvinlai/Documents/Projects/Text2Speech/bark/bark/__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform, save_as_prompt
  File "/Users/murvinlai/Documents/Projects/Text2Speech/bark/bark/api.py", line 5, in <module>
    from .generation import codec_decode, generate_coarse, generate_fine, generate_text_semantic
  File "/Users/murvinlai/Documents/Projects/Text2Speech/bark/bark/generation.py", line 8, in <module>
    from encodec import EncodecModel
ModuleNotFoundError: No module named 'encodec'

**Comment by gkucsko** [comment]
gonna close for inactivity. feel free to reopen if not fixed
