### ISSUE TITLE
ValueError: ERROR, something went wrong in preload_models

### ISSUE THREAD

**Issue by nhnansari** [suno-ai/bark#205]
I think I have missing some module installations,  I am getting the following error

`
  warnings.warn("No audio backend is available.")
No GPU being used. Careful, inference might be very slow!
found outdated coarse model, removing.
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                       | 3.39G/3.93G [52:02<08:16, 1.09MiB/s]
Traceback (most recent call last):
  File "C:\Users\alnad\OneDrive\Desktop\ConvertedMp3\Bark\barktest.py", line 7, in <module>
    preload_models()
  File "C:\Users\alnad\AppData\Local\Programs\Python\Python311\Lib\site-packages\bark\generation.py", line 356, in preload_models
    _ = load_model(
        ^^^^^^^^^^^
  File "C:\Users\alnad\AppData\Local\Programs\Python\Python311\Lib\site-packages\bark\generation.py", line 310, in load_model
    model = _load_model_f(ckpt_path, device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alnad\AppData\Local\Programs\Python\Python311\Lib\site-packages\bark\generation.py", line 246, in _load_model
    _download(model_info["path"], ckpt_path)
  File "C:\Users\alnad\AppData\Local\Programs\Python\Python311\Lib\site-packages\bark\generation.py", line 180, in _download
    raise ValueError("ERROR, something went wrong")
ValueError: ERROR, something went wrong
`

**Comment by gkucsko** [comment]
hm it looks like the download is failing? probably just try again? worst case you can manually download, but that's annoying since you have to put it in the right place after: https://github.com/suno-ai/bark/issues/46

**Comment by gkucsko** [comment]
gonna close for inactivity. feel free to reopen if not fixed
