### ISSUE TITLE
Does this work in vs-code for local development ?

### ISSUE THREAD

**Issue by drjkpalli** [suno-ai/bark#206]
Hi,
was not able to use the following code to generate the audio:
```
from bark import SAMPLE_RATE, generate_audio, preload_models
from IPython.display import Audio

# download and load all models
preload_models()

# generate audio from text
text_prompt = """
     Hello, my name is Suno. And, uh — and I like pizza. [laughs] 
     But I also have other interests such as playing tic tac toe.
"""
audio_array = generate_audio(text_prompt)

# play text in notebook
Audio(audio_array, rate=SAMPLE_RATE)
```

Got the following errror:

```
No GPU being used. Careful, inference might be very slow!
Traceback (most recent call last):
  File "/Users/jk/Library/CloudStorage/OneDrive-Personal/Medical AI/Test/test2.py", line 5, in <module>
    preload_models()
  File "/usr/local/lib/python3.10/site-packages/bark/generation.py", line 341, in preload_models
    _ = load_model(
  File "/usr/local/lib/python3.10/site-packages/bark/generation.py", line 298, in load_model
    model = _load_model_f(ckpt_path, device)
  File "/usr/local/lib/python3.10/site-packages/bark/generation.py", line 234, in _load_model
    _download(model_info["repo_id"], model_info["file_name"], ckpt_path)
  File "/usr/local/lib/python3.10/site-packages/bark/generation.py", line 168, in _download
    hf_hub_download(repo_id=from_hf_path, filename=file_name, local_dir=CACHE_DIR)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
TypeError: hf_hub_download() got an unexpected keyword argument 'local_dir'
```

**Comment by peremarshall** [comment]
The issue might be caused by an outdated version of the huggingface_hub library, @drjkpalli.

To fix the issue, please try updating the huggingface_hub library:

`pip install -U huggingface_hub`

**Comment by drjkpalli** [comment]
Yep. That was the issue. Thanks @peremarshall

**Comment by drjkpalli** [comment]
I am working with cpu only on a 2015 13 inch MacBook Pro with 8gb of ram. Any suggestions on what the best approach is with regards to the models or otherwise ??

**Comment by rubinchyk** [comment]
> The issue might be caused by an outdated version of the huggingface_hub library, @drjkpalli.
> 
> To fix the issue, please try updating the huggingface_hub library:
> 
> `pip install -U huggingface_hub`

Unfortunately same situation and this not helped.

**Comment by DizzyDJW** [comment]
Yea... I've tried every so-called "Fix" and I still can't get around that obnoxious error "found outdated text model, removing"

EVERY. SINGLE. FIX. has failed. Not even ChatGPT could rectify the issue. At this point I'm ready to remove the 20+GBs of useless junk I've downloaded in an attempt to get this to function. 16GB in the .cache folder alone.

**Comment by DizzyDJW** [comment]
> Apologies, we are debugging some issues with the new download method which we think is related to this.

Will it require a fresh download and install? I.E. Should I just delete the files on my computer and try again or will it be best to keep the several different ".pt" files I had to download individually, manually?

**Comment by MovLab2** [comment]
similar issue 

\anaconda3\lib\site-packages\bark\generation.py", line 168, in _download
    hf_hub_download(repo_id=from_hf_path, filename=file_name, local_dir=CACHE_DIR)
TypeError: hf_hub_download() got an unexpected keyword argument 'local_dir'

**Comment by MovLab2** [comment]
yes :)


-----Original Message-----
