### ISSUE TITLE
404 https://huggingface.co/suno/bark/coarse_2.pt 

### ISSUE THREAD

**Issue by samual30000** [suno-ai/bark#224]
404
Sorry, we can't find the page you are looking for. 

from bark import SAMPLE_RATE, generate_audio, preload_models
from IPython.display import Audio

# download and load all models
preload_models()

# generate audio from text
text_prompt = """
     Hello, my name is Suno. And, uh — and I like pizza. [laughs] 
     But I also have other interests such as playing tic tac toe.
"""
audio_array = generate_audio(text_prompt)

# play text in notebook
Audio(audio_array, rate=SAMPLE_RATE)

D:\Game\python\lib\site-packages\huggingface_hub\file_download.py:562: FutureWarning: `cached_download` is the legacy way to download files from the HF hub, please consider upgrading to `hf_hub_download`
  warnings.warn(
Traceback (most recent call last):
  File "D:\ALL\git\desktop\bark\go.py", line 6, in <module>
    preload_models()
  File "D:\ALL\git\desktop\bark\bark\generation.py", line 382, in preload_models
    _ = load_model(
  File "D:\ALL\git\desktop\bark\bark\generation.py", line 336, in load_model
    model = _load_model_f(ckpt_path, device)
  File "D:\ALL\git\desktop\bark\bark\generation.py", line 272, in _load_model
    _download(model_info["repo_id"], model_info["file_name"], ckpt_path)
  File "D:\ALL\git\desktop\bark\bark\generation.py", line 195, in _download
    local_file = cached_download(hf_url)
  File "D:\Game\python\lib\site-packages\huggingface_hub\utils\_deprecation.py", line 32, in inner_f
    return f(*args, **kwargs)
  File "D:\Game\python\lib\site-packages\huggingface_hub\file_download.py", line 605, in cached_download
    _raise_for_status(r)
  File "D:\Game\python\lib\site-packages\huggingface_hub\utils\_errors.py", line 78, in _raise_for_status
    request.raise_for_status()
  File "D:\Game\python\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/suno/bark/coarse_2.pt

**Comment by gkucsko** [comment]
try updating `huggingface_hub`

**Comment by gkucsko** [comment]
huggingface should take care of that automatically during download. did you download the file manually?

**Comment by jxyk2007** [comment]
https://huggingface.co/suno/bark/tree/main
download text_2.pt
