### ISSUE TITLE
raise RuntimeError(msg) RuntimeError: jaxlib is version 0.3.25, but this version of jax requires version >= 0.4.7.

### ISSUE THREAD

**Issue by huanggou666** [suno-ai/bark#242]
I have this bug msg, I couldn't find jaxlib file of 0.4.7 for windows,

**Comment by gkucsko** [comment]
hmm, no idea why jax would be needed. what's the stacktrace?

**Comment by huanggou666** [comment]
> 
This is the whole Traceback, I don't know if there is something wrong with my python environment or not.
Traceback (most recent call last):
  File "F:\New project\barkGUI\bark-gui\webui.py", line 13, in <module>
    from bark import SAMPLE_RATE, generate_audio
  File "F:\New project\barkGUI\bark-gui\bark\__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform, save_as_prompt
  File "F:\New project\barkGUI\bark-gui\bark\api.py", line 5, in <module>
    from .generation import codec_decode, generate_coarse, generate_fine, generate_text_semantic
  File "F:\New project\barkGUI\bark-gui\bark\generation.py", line 17, in <module>
    from transformers import BertTokenizer
  File "C:\Users\daihao\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\daihao\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Users\daihao\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\__init__.py", line 30, in <module>
    from .generic import (
  File "C:\Users\daihao\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import jax.numpy as jnp
  File "C:\Users\daihao\AppData\Local\Programs\Python\Python310\lib\site-packages\jax\__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "C:\Users\daihao\AppData\Local\Programs\Python\Python310\lib\site-packages\jax\config.py", line 17, in <module>
    from jax._src.config import config  # noqa: F401
  File "C:\Users\daihao\AppData\Local\Programs\Python\Python310\lib\site-packages\jax\_src\config.py", line 24, in <module>
    from jax._src import lib
  File "C:\Users\daihao\AppData\Local\Programs\Python\Python310\lib\site-packages\jax\_src\lib\__init__.py", line 73, in <module>
    version = check_jaxlib_version(
  File "C:\Users\daihao\AppData\Local\Programs\Python\Python310\lib\site-packages\jax\_src\lib\__init__.py", line 62, in check_jaxlib_version
    raise RuntimeError(msg)
RuntimeError: jaxlib is version 0.3.25, but this version of jax requires version >= 0.4.7.

**Comment by gkucsko** [comment]
weird, seems like it's coming from `transformers` maybe try updating transformers? or just jaxlib directly?

**Comment by huanggou666** [comment]
> 
updated transformers does not work, the problem is there is no 0.4.7 version of jaxlib on the internet for windows, the highest  version available is 0.3.7 [](,https://whls.blob.core.windows.net/unstable/index.html) 
 [cuda111/jaxlib-0.3.5+cuda11.cudnn82-cp310-none-win_amd64.whl](https://whls.blob.core.windows.net/unstable/cuda111/jaxlib-0.3.5+cuda11.cudnn82-cp310-none-win_amd64.whl)
The strange thing is that there are almost no questions and answers about the 0.4.7 version of Jaxlib on Google. I maybe the only one have this bug

**Comment by gkucsko** [comment]
strange ya sorry, don't really have good idea... did you try a fresh virtual environment to install stuff from scratch? shooting in the dark here a bit though

**Comment by shouldsee** [comment]
> > 
> 
> updated transformers does not work, the problem is there is no 0.4.7 version of jaxlib on the internet for windows, the highest version available is 0.3.7 [cuda111/jaxlib-0.3.5+cuda11.cudnn82-cp310-none-win_amd64.whl](https://whls.blob.core.windows.net/unstable/cuda111/jaxlib-0.3.5+cuda11.cudnn82-cp310-none-win_amd64.whl) The strange thing is that there are almost no questions and answers about the 0.4.7 version of Jaxlib on Google. I maybe the only one have this bug


You probably need to downgrade transformers, to make it compatible with your installed jaxlib

**Comment by gkucsko** [comment]
closing for inactivity, feel free to reopen if not fixed

**Comment by AditiPanda** [comment]
Hello @huanggou666 I'm getting the same error, were you able to solve this? I'm running the colab file of ViT.
