### ISSUE TITLE
Adding v2/ to history prompt will cause error

### ISSUE THREAD

**Issue by tin2tin** [suno-ai/bark#248]
As suggested here: https://github.com/suno-ai/bark/issues/193#issuecomment-1533670623

Adding this to the prompt: "v2/en_speaker_6" will cause this error:
```
Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\text_to_video-main\__init__.py", line 728, in execute
    audio = generate_audio(prompt, history_prompt=lan_speak)
  File "C:\Users\XXXX\AppData\Roaming\Python\Python310\site-packages\bark\api.py", line 107, in generate_audio
    semantic_tokens = text_to_semantic(
  File "C:\Users\XXXX\AppData\Roaming\Python\Python310\site-packages\bark\api.py", line 25, in text_to_semantic
    x_semantic = generate_text_semantic(
  File "C:\Users\XXXX\AppData\Roaming\Python\Python310\site-packages\bark\generation.py", line 385, in generate_text_semantic
    silent=False,
AssertionError
Error: Python: Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\text_to_video-main\__init__.py", line 728, in execute
    audio = generate_audio(prompt, history_prompt=lan_speak)
  File "C:\Users\XXXX\AppData\Roaming\Python\Python310\site-packages\bark\api.py", line 107, in generate_audio
    semantic_tokens = text_to_semantic(
  File "C:\Users\XXXX\AppData\Roaming\Python\Python310\site-packages\bark\api.py", line 25, in text_to_semantic
    x_semantic = generate_text_semantic(
  File "C:\Users\XXXX\AppData\Roaming\Python\Python310\site-packages\bark\generation.py", line 385, in generate_text_semantic
    silent=False,
AssertionError
```

**Comment by gkucsko** [comment]
are you on the newest version of bark? does `v2/en_speaker_5` work? does `en_speaker_5` work?

**Comment by tin2tin** [comment]
V2/ gave me an error both before and after the update.

**Comment by gkucsko** [comment]
without v2 are the old prompts so that makes sense, but you should also be able to use the new ones. would love to figure out why but hard for me to reproduce

**Comment by tin2tin** [comment]
Apparently the python module wasn't properly updated. I needed first to manually remove the side package, to get it to install.

**Comment by headkit** [comment]
what side package?
