### ISSUE TITLE
preload_models() error

### ISSUE THREAD

**Issue by liyang-d1c3y7** [suno-ai/bark#258]
执行preload_models()报错：

Traceback (most recent call last):
  File "my_generation.py", line 17, in <module>
    preload_models()
  File "/ossfs/workspace/bark/bark/generation.py", line 318, in preload_models
    _ = load_model(
  File "/ossfs/workspace/bark/bark/generation.py", line 275, in load_model
    model = _load_model_f(ckpt_path, device)
  File "/ossfs/workspace/bark/bark/generation.py", line 211, in _load_model
    _download(model_info["repo_id"], model_info["file_name"])
  File "/ossfs/workspace/bark/bark/generation.py", line 151, in _download
    hf_hub_download(repo_id=from_hf_path, filename=file_name, local_dir=CACHE_DIR)
  File "/root/miniconda3/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
TypeError: hf_hub_download() got an unexpected keyword argument 'local_dir'
(base)

**Comment by albertshao** [comment]
@liyang-d1c3y7  I fixed by upgrading huggingface_hub by the following command. 
pip install --upgrade huggingface_hub

**Comment by gkucsko** [comment]
great! i think the folks for huggingface were gonna add a min requirements some time tomorrow or so. (not exactly sure what minimum version is required rn)
