### ISSUE TITLE
IndexError: index out of range in self

### ISSUE THREAD

**Issue by allanming** [suno-ai/bark#278]
``` python
# demo.py"
from bark import SAMPLE_RATE, generate_audio, preload_models
from scipy.io.wavfile import write as write_wav
from IPython.display import Audio

# download and load all models
preload_models()

# generate audio from text
text_prompt = """
     Hello, my name is Suno. And, uh — and I like pizza. [laughs] 
     But I also have other interests such as playing tic tac toe.
"""
audio_array = generate_audio(text_prompt)

# save audio to disk
write_wav("bark_generation.wav", SAMPLE_RATE, audio_array)
  
# play text in notebook
Audio(audio_array, rate=SAMPLE_RATE)
```
``` shell
python demo.py
```

``` shell
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:40<00:00,  2.44it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 36/36 [01:17<00:00,  2.17s/it]
Traceback (most recent call last):
  File "/Users/allan/Work/OpenAI/bark/demo.py", line 13, in <module>
    audio_array = generate_audio(text_prompt)
  File "/Users/allan/Work/OpenAI/bark/bark/api.py", line 113, in generate_audio
    out = semantic_to_waveform(
  File "/Users/allan/Work/OpenAI/bark/bark/api.py", line 66, in semantic_to_waveform
    audio_arr = codec_decode(fine_tokens)
  File "/Users/allan/Work/OpenAI/bark/bark/generation.py", line 830, in codec_decode
    emb = model.quantizer.decode(arr)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/encodec/quantization/vq.py", line 112, in decode
    quantized = self.vq.decode(codes)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/encodec/quantization/core_vq.py", line 361, in decode
    quantized = layer.decode(indices)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/encodec/quantization/core_vq.py", line 288, in decode
    quantize = self._codebook.decode(embed_ind)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/encodec/quantization/core_vq.py", line 202, in decode
    quantize = self.dequantize(embed_ind)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/encodec/quantization/core_vq.py", line 188, in dequantize
    quantize = F.embedding(embed_ind, self.embed)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```
What is the reason for this? How to solve?

**Comment by gkucsko** [comment]
super strange, haven't seen that. maybe upgrade torch?

**Comment by leejr72** [comment]
I had similar issues when mixing the installs of the dependancies conda install vs pip install when running on MacBook Pro M2.

### Install instructions
Bark MPS
git clone https://github.com/suno-ai/bark
cd bark
conda create -n bark python=3.10
conda activate bark
pip install . 
pip uninstall -y torch torchvision torchaudio 
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu


### Python code execute in Jupiter

import os
os.environ["SUNO_ENABLE_MPS"] = "True"

from bark import SAMPLE_RATE, generate_audio, preload_models
from scipy.io.wavfile import write as write_wav
from IPython.display import Audio

# download and load all models
preload_models()

# generate audio from text
text_prompt = """
     Hello, I am called BARK and am a new text to audio model made by SUNO!
     Let me read an excerpt from War of the Worlds to you. [clears throat]
"""
audio_array = generate_audio(text_prompt)

# save audio to disk
write_wav("bark_generation.wav", SAMPLE_RATE, audio_array)

# play text in notebook
Audio(audio_array, rate=SAMPLE_RATE)

![Screenshot 2023-05-13 at 5 32 24 PM](https://github.com/suno-ai/bark/assets/110568703/77f33799-a4c2-4b9c-bec0-3ba4c597bb92)
