### ISSUE TITLE
preload_models just gives a RuntimeError

### ISSUE THREAD

**Issue by gavtography** [suno-ai/bark#334]
Just trying to run the example code. It doesn't work:

```
from bark import SAMPLE_RATE, generate_audio, preload_models
from scipy.io.wavfile import write as write_wav
from IPython.display import Audio


# download and load all models
preload_models()

# generate audio from text
text_prompt = """
     Hello, my name is Suno. And, uh — and I like pizza. [laughs] 
     But I also have other interests such as playing tic tac toe.
"""
audio_array = generate_audio(text_prompt)

# save audio to disk
write_wav("bark_generation.wav", SAMPLE_RATE, audio_array)
  
# play text in notebook
Audio(audio_array, rate=SAMPLE_RATE)
```

```
Exception has occurred: RuntimeError
invalid hash value (expected "d7cc33bc", got "64d6b75683a6ea0521297b2f43bcb2ab549101f30510751b3f21b2c0391924dd")
  File "C:\Users\USER\Desktop\tts_test.py", line 7, in <module>
    preload_models()
RuntimeError: invalid hash value (expected "d7cc33bc", got "64d6b75683a6ea0521297b2f43bcb2ab549101f30510751b3f21b2c0391924dd")
```

**Comment by banls** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/bark/bark/generation.py", line 318, in preload_models
    _ = load_model(
  File "/root/bark/bark/generation.py", line 275, in load_model
    model = _load_model_f(ckpt_path, device)
  File "/root/bark/bark/generation.py", line 211, in _load_model
    _download(model_info["repo_id"], model_info["file_name"])
  File "/root/bark/bark/generation.py", line 151, in _download
    hf_hub_download(repo_id=from_hf_path, filename=file_name, local_dir=CACHE_DIR)
  File "/anaconda3/envs/bark/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/anaconda3/envs/bark/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1291, in hf_hub_downloa
d
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the d
isk cache. Please try again or make sure your Internet connection is on.

**Comment by nanasemaik** [comment]
me too.How to download the models individually?
