### ISSUE TITLE
AttributeError: module 'torch.cuda' has no attribute 'is_bf16_supported'

### ISSUE THREAD

**Issue by 5118Python** [suno-ai/bark#40]
Traceback (most recent call last):
  File "D:\5118\movielearning\testbark\test.py", line 1, in <module>
    from bark import SAMPLE_RATE, generate_audio
  File "C:\ProgramData\Anaconda3\envs\movielearning\lib\site-packages\bark\__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform
  File "C:\ProgramData\Anaconda3\envs\movielearning\lib\site-packages\bark\api.py", line 5, in <module>
    from .generation import codec_decode, generate_coarse, generate_fine, generate_text_semantic
  File "C:\ProgramData\Anaconda3\envs\movielearning\lib\site-packages\bark\generation.py", line 24, in <module>
    torch.cuda.is_bf16_supported()
AttributeError: module 'torch.cuda' has no attribute 'is_bf16_supported'

**Comment by gkucsko** [comment]
eeek, didn't know that can happen in some torch versions. will fix tyty

**Comment by gkucsko** [comment]
fixed in https://github.com/suno-ai/bark/commit/c3724301125c3ba4401c89958ca8612201282ec0
