### ISSUE TITLE
Problem running command line

### ISSUE THREAD

**Issue by ppazos** [suno-ai/bark#406]
I'm not a python dev, not sure what this error is. Just wanted to try this library.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/pablo/GitHub/bark/bark/__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform, save_as_prompt
  File "/home/pablo/GitHub/bark/bark/api.py", line 3, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by yangboz** [comment]
> I'm not a python dev, not sure what this error is. Just wanted to try this library.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
>     __import__(pkg_name)
>   File "/home/pablo/GitHub/bark/bark/__init__.py", line 1, in <module>
>     from .api import generate_audio, text_to_semantic, semantic_to_waveform, save_as_prompt
>   File "/home/pablo/GitHub/bark/bark/api.py", line 3, in <module>
>     import numpy as np
> ModuleNotFoundError: No module named 'numpy'
> ```

you need cd bark,  pip install . at first which include numpy module.

**Comment by f1am3d** [comment]
Same here. 
I did everything in accordance with the installation instructions.

**Comment by f1am3d** [comment]
Okay, figured this out. Steps:


1. `pip install . --force`
result: `ModuleNotFoundError: No module named 'numpy'`

2. `pip install numpy`

3. `python example.py`
Result: `ModuleNotFoundError: No module named 'IPython'`

4. `pip install ipython`
5. `python example.py`
Result: success.

OS: Windows 11
