### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by Razbolt** [suno-ai/bark#428]
Hi guys, 
This issue already has been closed but I do not find any relative solution. I'm trying to work on cloning a vocie however, I have found an error while I am working on a bark model. I have cloned the bark repository and made a checkpoint, still got an error as below : 
 `` (bark) PS C:\Users\arsla\TTs-Bark> python voice_clone.py
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 17.4k/17.4k [00:00<?, ?iB/s] 
Traceback (most recent call last):
  File "C:\Users\arsla\TTs-Bark\voice_clone.py", line 14, in <module>
    model.load_checkpoint(config, checkpoint_dir = "bark/", eval = True)
  File "C:\Users\arsla\anaconda3\envs\bark\lib\site-packages\TTS\tts\models\bark.py", line 275, in load_checkpoint
    self.load_bark_models()
  File "C:\Users\arsla\anaconda3\envs\bark\lib\site-packages\TTS\tts\models\bark.py", line 50, in load_bark_models
    self.semantic_model, self.config = load_model(
  File "C:\Users\arsla\anaconda3\envs\bark\lib\site-packages\TTS\tts\layers\bark\load_model.py", line 121, in load_model
    checkpoint = torch.load(ckpt_path, map_location=device)
  File "C:\Users\arsla\anaconda3\envs\bark\lib\site-packages\torch\serialization.py", line 815, in load
  File "C:\Users\arsla\anaconda3\envs\bark\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'. ``

I have not found any solution for it and I think some people still got the same error. Any ideas ?

**Comment by GuiguiBlitz** [comment]
Hello, i first had this issue because i didn't use lfs support for git when cloning bark repo from hugging faces. You might have the same issue.

**Comment by Razbolt** [comment]
> Hello, i first had this issue because i didn't use lfs support for git when cloning bark repo from hugging faces. You might have the same issue.

Hey thank you for your feedback, I swicthed my environment VSCode to Google Colab and I resolve this problem by that. Probably I will need to use in VSCode so how can I support lfs for git ?

**Comment by omarkashif** [comment]
Install lfs by: git lfs install
Then clone the repo: GIT_LFS_SKIP_SMUDGE=1 git clone REPO_NAME
