### ISSUE TITLE
Building wheel for safetensors (pyproject.toml) did not run successfully.

### ISSUE THREAD

**Issue by Ashmit12092000** [suno-ai/bark#435]
While installing suno-bark i'm enconutering  this error 
error: subprocess-exited-with-error

  × Building wheel for safetensors (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\safetensors
      copying py_src\safetensors\flax.py -> build\lib.win-amd64-cpython-311\safetensors
      copying py_src\safetensors\numpy.py -> build\lib.win-amd64-cpython-311\safetensors
      copying py_src\safetensors\paddle.py -> build\lib.win-amd64-cpython-311\safetensors
      copying py_src\safetensors\tensorflow.py -> build\lib.win-amd64-cpython-311\safetensors
      copying py_src\safetensors\torch.py -> build\lib.win-amd64-cpython-311\safetensors
      copying py_src\safetensors\__init__.py -> build\lib.win-amd64-cpython-311\safetensors
      running build_ext
      running build_rust
      error: can't find Rust compiler

      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

      To update pip, run:

          pip install --upgrade pip

      and then retry package installation.

      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for safetensors
Successfully built suno-bark
Failed to build safetensors
ERROR: Could not build wheels for safetensors, which is required to install pyproject.toml-based projects

**Comment by venturaEffect** [comment]
Same here.

Using windows 11.

Tnaks for creating the issue.

**Comment by dokim3014** [comment]
error: can't find Rust compiler <-- This part is the main problem.

Install Rust by downloading it from the official website.
(https://www.rust-lang.org/tools/install)

By default Rust will add PATH.

Reload and try "pip install transformers" again.

This worked for me.

**Comment by venturaEffect** [comment]
Thanks a lot @dokim3014 .

But now I get this error message and can't figure out why?

`Traceback (most recent call last):
  File "C:\Users\zaesa\Downloads\Bark_WebUI\bark\UI.py", line 1, in <module>
    from bark import SAMPLE_RATE, generate_audio
  File "C:\Users\zaesa\Downloads\Bark_WebUI\bark\bark\__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform, save_as_prompt
  File "C:\Users\zaesa\Downloads\Bark_WebUI\bark\bark\api.py", line 5, in <module>
    from .generation import codec_decode, generate_coarse, generate_fine, generate_text_semantic
  File "C:\Users\zaesa\Downloads\Bark_WebUI\bark\bark\generation.py", line 6, in <module>
    from encodec import EncodecModel
ModuleNotFoundError: No module named 'encodec'

Done!`

Any suggestion? Appreciate

**Comment by dokim3014** [comment]
You don't have 'encodec' library. In your virtual environment, run "pip
install encodec" and it will be solved.

2023년 8월 24일 (목) 오후 4:45, Cesar Romero ***@***.***>님이 작성:

**Comment by Ashmit12092000** [comment]
> I solved the issue by downgrading python version from 3.11 to 3.8 . No need to down rust compiler additionally

**Comment by iamrexan** [comment]
After installing Rust, issue resolved to me.
