### ISSUE TITLE
Hugging face optimized implementation fails. 

### ISSUE THREAD

**Issue by kamyarkarimi** [suno-ai/bark#468]
I am following https://huggingface.co/docs/transformers/model_doc/bark#combining-optimizaton-techniques. I am on a single gpu ml.g5.16xlarge Linux machine on AWS Sagemekr (specs: https://aws.amazon.com/ec2/instance-types/g5/) . I have already installed the bark from its git repo, and have it working with no issues on this machine. The issue comes in when I try to implement this optimized form described. I have exactly copied and paste the code, and get the following error, when I do the `audio_array = model.generate(**inputs)`

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)

```
from transformers import AutoProcessor, BarkModel
from IPython.display import Audio
import torch
from optimum.bettertransformer import BetterTransformer
device = "cuda" if torch.cuda.is_available() else "cpu"

# load in fp16
model = BarkModel.from_pretrained("suno/bark-small", torch_dtype=torch.float16).to(device)

# convert to bettertransformer
model = BetterTransformer.transform(model, keep_original_model=False)

# enable CPU offload
model.enable_cpu_offload()

processor = AutoProcessor.from_pretrained("suno/bark")
# model = BarkModel.from_pretrained("suno/bark")

voice_preset = "v2/en_speaker_6"

inputs = processor("Hi, my name is Frank", voice_preset=voice_preset)
audio_array = model.generate(**inputs)
audio_array = audio_array.cpu().numpy().squeeze()
```

**Comment by Cazforshort** [comment]
Try putting the inputs on the device too.

**Comment by smithedits** [comment]
Did you figure it out?

**Comment by smartvnm** [comment]
inputs = processor("Hi, my name is Frank", voice_preset=voice_preset).to(device)
That's all you need

**Comment by jhj0517** [comment]
> `inputs= processor("Hi, my name is Frank", voice_preset=voice_preset).to(device)` That's all you need

AttributeError: 'BarkProcessor' object has no attribute 'to'

Is there any other way to put the processor on the device?
I keep finding it, but I can't.

**Comment by PhilipAmadasun** [comment]
@smartvnm  This worked for me but now I get `ValueError: Unsupported data type 'float16'` when I try to save .wav file with scipy

**Comment by foxumulder2017** [comment]
this worked for me:

apparently, not all tensors under `inputs` are moved to cuda when this is called:

```
inputs.to(device)
```

I moved the voice_preset tensors first to cuda before moving the inputs.

```
# load npz file
import numpy

# manually create the voice_preset dict
with numpy.load('bark/assets/prompts/en_speaker_6.npz') as data:
    voice_preset = {
    'fine_prompt':data['fine_prompt'],
    'coarse_prompt':data['coarse_prompt'],
    'semantic_prompt':data['semantic_prompt']
    }


text_prompt = "sample text prompt"
inputs = processor(text_prompt,voice_preset=voice_preset)
inputs['history_prompt'] = inputs['history_prompt'].to(device)
inputs.to(device)
```

**Comment by emircanerkul** [comment]
Facing similar issue, where am i missing? (I almost put everywhere to(device) 😀)
Code
```py
from transformers import AutoProcessor, BarkModel
import scipy, torch


device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
processor = AutoProcessor.from_pretrained("suno/bark", torch_dtype=torch.float16)
model = BarkModel.from_pretrained("suno/bark", torch_dtype=torch.float16)
model = model.to(device)

voice_preset = "v2/tr_speaker_4"

inputs = processor("y  r  ko ^=lu yar  m ya ^=l   yo ^=urt be ^= kilogram y  z k  rk dokuz lira", voice_preset=voice_preset).to(device)

audio_array = model.to(device).generate(**inputs)
audio_array = audio_array.cuda().numpy().squeeze()

sample_rate = model.generation_config.sample_rate
scipy.io.wavfile.write("bark_out.wav", rate=sample_rate, data=audio_array)
```

Error
```
/home/yyyyyy/miniconda3/lib/python3.12/site-packages/transformers/models/encodec/modeling_encodec.py:124: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.register_buffer("padding_total", torch.tensor(kernel_size - stride, dtype=torch.int64), persistent=False)
Traceback (most recent call last):
  File "/home/yyyyyy/bark/a.py", line 15, in <module>
    audio_array = model.to(device).generate(**inputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yyyyyy/miniconda3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/yyyyyy/miniconda3/lib/python3.12/site-packages/transformers/models/bark/modeling_bark.py", line 1726, in generate
    semantic_output = self.semantic.generate(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yyyyyy/miniconda3/lib/python3.12/site-packages/transformers/models/bark/modeling_bark.py", line 878, in generate
    + self.input_embeds_layer(semantic_history[:, : max_input_semantic_length + 1]),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yyyyyy/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yyyyyy/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yyyyyy/miniconda3/lib/python3.12/site-packages/torch/nn/modules/sparse.py", line 190, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "/home/yyyyyy/miniconda3/lib/python3.12/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
```

**Comment by emircanerkul** [comment]
```
    inputs = {
        k: v.to(device) if hasattr(v, 'to') else v
        for k, v in inputs.items()
    }
```

this solved. Glory to claude 3.5!

**Comment by HarshPatil89** [comment]
> ```
>     inputs = {
>         k: v.to(device) if hasattr(v, 'to') else v
>         for k, v in inputs.items()
>     }
> ```
> 
> this solved. Glory to claude 3.5!

Please add whole code

**Comment by ghost** [comment]
## Bark's BatchEncoding

This seems like a bug in either
1.  `transformers.models.bert.tokenization_bert.BertTokenizer` (MRO is `BertTokenizer < PreTrainedTokenizer < PreTrainedTokenizerBase`) or
    - In this case `__call__` should be adjusted to return a subclass of `BatchEncoding`
2. `transformers.tokenization_utils_base.BatchEncoding.to`
    - In this case the implementation should be recursive in order to be generic

If any of you has some experience with the structure and workflows of [huggingface/transformers](https://github.com/huggingface/transformers) (I don't), please create an issue there.

---

**Update:** The docstring of `BatchEncoding` says:

> ```
> Args:
>     data (`dict`, *optional*):
>         Dictionary of lists/arrays/tensors returned by the `__call__`/`encode_plus`/`batch_encode_plus` methods
>         ('input_ids', 'attention_mask', etc.).
> ```

so it seems option 2. is more appropriate (even though nested dicts are not documented).

The current implementation of `.to` does
```python
self.data = {
    k: v.to(device=device, non_blocking=non_blocking) if isinstance(v, torch.Tensor) else v
    for k, v in self.data.items()
}
```
which is basically what was suggested in https://github.com/suno-ai/bark/issues/468#issuecomment-2597615675

So since the tensors in the nested dicts
```python
{
    'input_ids': tensor([[...]]),
    'attention_mask': tensor([[...]]),
    'history_prompt': {
      'coarse_prompt': tensor([[...]]),
      'fine_prompt': tensor([[...]]),
      'semantic_prompt': tensor([[...]]),
    },
}
```
 returned by the processor also need to moved.

## Solution

```python
BatchEncoding = Mapping[str, Union[Tensor, "BatchEncoding", list["BatchEncoding"]]]
# >=Python 3.12
# type BatchEncoding = Mapping[str, Tensor | BatchEncoding | list[BatchEncoding]]


def move_inputs_to_device(
    encoding: BatchEncoding,
    device: torch.device,
) -> BatchEncoding:
    def move_recursive(data: Tensor | BatchEncoding | Sequence[BatchEncoding]):
        if isinstance(data, Mapping):
            return {k: move_recursive(v) for k, v in data.items()}
        elif isinstance(data, Sequence):
            return [move_recursive(v) for v in data]
        elif isinstance(data, torch.Tensor):
            return data.to(device)
        else:
            raise TypeError(
                f"Expected 'Tensor | BatchEncoding | Sequence[BatchEncoding]' "
                f"but got {type(data)}"
            )

    return {k: move_recursive(v) for k, v in encoding.items()}
```

## Usage

```python
inputs = inputs_processor(text, voice_preset=VOICE_PRESET, return_tensors="pt")
inputs = move_inputs_to_device(inputs, device)
audio_array = model.generate(**inputs)
```
