### ISSUE TITLE
Please help me to fix this issue : not able to download models

### ISSUE THREAD

**Issue by parthagorai** [suno-ai/bark#486]
(bark) ai@aiserver:/mnt/apps/voice-clone$ python tts.py
Traceback (most recent call last):
  File "/mnt/apps/voice-clone/tts.py", line 4, in <module>
    preload_models()
  File "/mnt/apps/voice-clone/bark/generation.py", line 368, in preload_models
    _ = load_model(
  File "/mnt/apps/voice-clone/bark/generation.py", line 316, in load_model
    if path.endswith(".ckpt") or path.endswith(".pt") or path.endswith(".bin"):
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by wildcat7534** [comment]
Hello, idem juste after I install hubert for cloning voice and I succes to make a model but 
I was enable to re load bark with the same result like you : 

File "/mnt/apps/voice-clone/bark/generation.py", line 368, in preload_models
_ = load_model(
File "/mnt/apps/voice-clone/bark/generation.py", line 316, in load_model
if path.endswith(".ckpt") or path.endswith(".pt") or path.endswith(".bin"):
AttributeError: 'NoneType' object has no attribute 'endswith'

I tried to re clone and another file and launch a exemple but same problem...

**Comment by wildcat7534** [comment]
I have found ! 

In your bark/generation.py

I give the path to the models 
ligne : 349 
`def preload_models(
    text_use_gpu=True,
    text_use_small=False,
    text_model_path="models/text_2.pt", #give the good path to the text model
    coarse_use_gpu=True,
    coarse_use_small=False,
    coarse_model_path="models/coarse_2.pt", #give the good path to the coarse model
    fine_use_gpu=True,
    fine_use_small=False,
    fine_model_path="models/fine_2.pt", #give the good path to the fine model
    codec_use_gpu=True,
    force_reload=False,
    path=None,
): ....`
