### ISSUE TITLE
Error when tried to use with coqui TTS

### ISSUE THREAD

**Issue by drishyakarki** [suno-ai/bark#487]
I cloned the suno-bark from huggingface and followed the docs, when i try to clone voice it gives the following error

the code is 
```
from TTS.tts.configs.bark_config import BarkConfig
from TTS.tts.models.bark import Bark
from scipy.io.wavfile import write as write_wav

config = BarkConfig()
model = Bark.init_from_config(config)
model.load_checkpoint(config, checkpoint_dir="bark/", eval=True)
model.to("cuda")

text = "Hi this is me Barack Obama"

output_dict = model.synthesize(
    text,
    config,
    speaker_id="speaker",
    voice_dirs="bark_voices",
    temperature=0.95
)

write_wav("output.wav", 24000, output_dict["wav"])
```

the error is
```
Traceback (most recent call last):
  File "/home/peshal/drishya/barkTTS/cloneVoice.py", line 7, in <module>
    model.load_checkpoint(config, checkpoint_dir="bark/", eval=True)
  File "/home/peshal/drishya/barkTTS/venv/lib/python3.10/site-packages/TTS/tts/models/bark.py", line 281, in load_checkpoint
    self.load_bark_models()
  File "/home/peshal/drishya/barkTTS/venv/lib/python3.10/site-packages/TTS/tts/models/bark.py", line 50, in load_bark_models
    self.semantic_model, self.config = load_model(
  File "/home/peshal/drishya/barkTTS/venv/lib/python3.10/site-packages/TTS/tts/layers/bark/load_model.py", line 121, in load_model
    checkpoint = torch.load(ckpt_path, map_location=device)
  File "/home/peshal/drishya/barkTTS/venv/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/peshal/drishya/barkTTS/venv/lib/python3.10/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

**Comment by drishyakarki** [comment]
Hi, so it was a simple mistake! I didn't have git lfs installed!

**Comment by ShanthiniMichael** [comment]
Didn't work for me. Any other solution? Thanks in advance.

**Comment by drishyakarki** [comment]
what is the error you got?

**Comment by ShanthiniMichael** [comment]
I am trying to clone again after installing git-lfs. But it is not downloading, it is almost 1 hour, but still not cloning the project.

**Comment by drishyakarki** [comment]
First remove the before-cloned folders, then try executing the command. Sometimes, if the download stucked, cancelling it and re-running the command helped.

**Comment by ShanthiniMichael** [comment]
I have tried like 10 times. It is not downloading.

```
Cloning into 'bark'...
remote: Enumerating objects: 847, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 847 (delta 13), reused 0 (delta 0), pack-reused 821
Receiving objects: 100% (847/847), 1.55 MiB | 2.68 MiB/s, done.
Resolving deltas: 100% (26/26), done.
Filtering content:  12% (95/790), 824.61 KiB | 8.00 KiB/s
```  


It is getting stuck at 12%. Kindly help me to solve this. Thanks in advance.

**Comment by ShanthiniMichael** [comment]
Thank you worked :).
