### ISSUE TITLE
Need help! No module numpy found

### ISSUE THREAD

**Issue by Nicolol1234** [suno-ai/bark#490]
Traceback (most recent call last):
  File "C:/Users/nicol/Desktop/Bark tts/bark/TTS.py", line 1, in <module>
    from bark import SAMPLE_RATE, generate_audio, preload_models
  File "C:\Users/nicol/Desktop/Bark tts/bark\bark\__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform, save_as_prompt
  File "C:\Users/nicol/Desktop/Bark tts/bark\bark\api.py", line 3, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

When i try to run , i got this error

**Comment by shoaib42** [comment]
I guess that means you'll need the numpy module.
`pip install numpy`

**Comment by Nicolol1234** [comment]
Already done, but still not working

**Comment by shoaib42** [comment]
Can you try with this instead, use the right executable. I suspect you may have multiple python environments. Use the same python exe that you use for running bark
`python.exe -m pip install numpy`

**Comment by cocomomedia** [comment]
Try `python.exe -m pip install .` from the `.\bark" directory to ensure you're not installing various versions independently from one another.
