### ISSUE TITLE
WebUI error

### ISSUE THREAD

**Issue by alexxony** [suno-ai/bark#503]
when I tried to 

python3 bark_webui.py --share 

`Traceback (most recent call last):
  File "bark_webui.py", line 1520, in <module>
    audio_prompt_input = gr.Audio(
  File "/usr/local/lib/python3.8/dist-packages/gradio/component_meta.py", line 155, in wrapper
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'info'`

How Can I solve this problem?

**Comment by Stefan-Gernhardt** [comment]
> when I tried to
> 
> python3 bark_webui.py --share
> 
> `Traceback (most recent call last): File "bark_webui.py", line 1520, in <module> audio_prompt_input = gr.Audio( File "/usr/local/lib/python3.8/dist-packages/gradio/component_meta.py", line 155, in wrapper return fn(self, **kwargs) TypeError: __init__() got an unexpected keyword argument 'info'`
> 
> How Can I solve this problem?

same for me

**Comment by JonathanFly** [comment]
This is my fault not Suno. The Bark fork you want is at https://github.com/JonathanFly/bark

You can find me in the Suno Discord though. I'll fix this tomorrow (Thursday) evening.
