### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'compiler'

### ISSUE THREAD

**Issue by MGW68** [suno-ai/bark#524]
I followed the install instructions.
When I try starting with START_BARK_INFINITY.bat, this is the error I get.
-----------------------------------------------------------------------------------
Running command: "C:\Bark_Infinity\installer_files\conda\condabin\conda.bat" activate "C:\Bark_Infinity\installer_files\env" >nul && conda
Running command: "C:\Bark_Infinity\installer_files\conda\condabin\conda.bat" activate "C:\Bark_Infinity\installer_files\env" >nul && python bark_webui.py
Traceback (most recent call last):
  File "C:\Bark_Infinity\bark\bark_webui.py", line 14, in <module>
    from bark_infinity import config
  File "C:\Bark_Infinity\bark\bark_infinity\__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform, save_as_prompt
  File "C:\Bark_Infinity\bark\bark_infinity\api.py", line 30, in <module>
    from .clonevoice import wav_to_semantics, generate_fine_from_wav, quick_clone
  File "C:\Bark_Infinity\bark\bark_infinity\clonevoice.py", line 33, in <module>
    from bark_infinity.hubert.pre_kmeans_hubert import CustomHubert
  File "C:\Bark_Infinity\bark\bark_infinity\hubert\pre_kmeans_hubert.py", line 20, in <module>
    from audiolm_pytorch.utils import curtail_to_multiple
  File "C:\Bark_Infinity\installer_files\env\lib\site-packages\audiolm_pytorch\__init__.py", line 8, in <module>
    from audiolm_pytorch.audiolm_pytorch import AudioLM
  File "C:\Bark_Infinity\installer_files\env\lib\site-packages\audiolm_pytorch\audiolm_pytorch.py", line 23, in <module>
    from audiolm_pytorch.soundstream import SoundStream
  File "C:\Bark_Infinity\installer_files\env\lib\site-packages\audiolm_pytorch\soundstream.py", line 20, in <module>
    from vector_quantize_pytorch import GroupedResidualVQ
  File "C:\Bark_Infinity\installer_files\env\lib\site-packages\vector_quantize_pytorch\__init__.py", line 2, in <module>
    from vector_quantize_pytorch.residual_vq import ResidualVQ, GroupedResidualVQ
  File "C:\Bark_Infinity\installer_files\env\lib\site-packages\vector_quantize_pytorch\residual_vq.py", line 13, in <module>
    from einx import get_at
  File "C:\Bark_Infinity\installer_files\env\lib\site-packages\einx\__init__.py", line 7, in <module>
    from . import backend
  File "C:\Bark_Infinity\installer_files\env\lib\site-packages\einx\backend\__init__.py", line 27, in <module>
    _update()
  File "C:\Bark_Infinity\installer_files\env\lib\site-packages\einx\backend\__init__.py", line 25, in _update
    backends.append(backend_factories[backend_name]())
  File "C:\Bark_Infinity\installer_files\env\lib\site-packages\einx\backend\_torch.py", line 127, in make_torch_backend
    einx.lru_cache.decorate_traced_functions(torch_.compiler.allow_in_graph)
AttributeError: module 'torch' has no attribute 'compiler'
If there is an error, take note of it here.

**Comment by crw123** [comment]
Hello, have you resolved the issue？

**Comment by MGW68** [comment]
> Hello, have you resolved the issue？

Never did get it to work by following the instructions. I just used Pinokio to install it, and it's working now.

**Comment by rsxdalv** [comment]
@JonathanFly This issue might have never went to the right repo.

**Comment by rsxdalv** [comment]
> Hello, have you resolved the issue？

Seems like fferflo/einx was updated, so if you can just `pip install ...` the newer version it should resolve this problem.
