### ISSUE TITLE
ModuleNotFoundError while trying to load entry-point bdist_wheel: No module named '_ctypes'

### ISSUE THREAD

**Issue by mozgbrasil** [suno-ai/bark#543]
Hello my friends, I downloaded the repository and tried to install the dependencies but the following error is returned. Anyone who can help me, I appreciate it

```
marcio@marcio-Inspiron-5548:~/dados/git-clones/pessoal/bash-labs/python/bark$ python --version
Python 3.10.14
marcio@marcio-Inspiron-5548:~/dados/git-clones/pessoal/bash-labs/python/bark$ pwd
/home/marcio/dados/git-clones/pessoal/bash-labs/python/bark
marcio@marcio-Inspiron-5548:~/dados/git-clones/pessoal/bash-labs/python/bark$ pip install .
Processing /home/marcio/dados/git-clones/pessoal/bash-labs/python/bark
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      ModuleNotFoundError while trying to load entry-point bdist_wheel: No module named '_ctypes'
      running dist_info
      creating /tmp/pip-modern-metadata-a2yk8egt/suno_bark.egg-info
      writing /tmp/pip-modern-metadata-a2yk8egt/suno_bark.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-a2yk8egt/suno_bark.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-modern-metadata-a2yk8egt/suno_bark.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-a2yk8egt/suno_bark.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-a2yk8egt/suno_bark.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-modern-metadata-a2yk8egt/suno_bark.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-modern-metadata-a2yk8egt/suno_bark.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-a2yk8egt/suno_bark-0.0.1a0.dist-info'
      Traceback (most recent call last):
        File "/home/marcio/.pyenv/versions/3.10.14/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/marcio/.pyenv/versions/3.10.14/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/marcio/.pyenv/versions/3.10.14/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-hr_d5ood/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-hr_d5ood/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
        File "/tmp/pip-build-env-hr_d5ood/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-hr_d5ood/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-hr_d5ood/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-hr_d5ood/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-hr_d5ood/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-hr_d5ood/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-hr_d5ood/overlay/lib/python3.10/site-packages/setuptools/command/dist_info.py", line 97, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
        File "/tmp/pip-build-env-hr_d5ood/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
        File "/tmp/pip-build-env-hr_d5ood/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 860, in get_command_obj
          klass = self.get_command_class(command)
        File "/tmp/pip-build-env-hr_d5ood/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 714, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/home/marcio/.pyenv/versions/3.10.14/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
          module = import_module(match.group('module'))
        File "/home/marcio/.pyenv/versions/3.10.14/lib/python3.10/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/tmp/pip-build-env-hr_d5ood/normal/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 27, in <module>
          from .macosx_libfile import calculate_macosx_platform_tag
        File "/tmp/pip-build-env-hr_d5ood/normal/lib/python3.10/site-packages/wheel/macosx_libfile.py", line 43, in <module>
          import ctypes
        File "/home/marcio/.pyenv/versions/3.10.14/lib/python3.10/ctypes/__init__.py", line 8, in <module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
marcio@marcio-Inspiron-5548:~/dados/git-clones/pessoal/bash-labs/python/bark$ 

```

![Captura de tela de 2024-03-25 21-53-19](https://github.com/suno-ai/bark/assets/17202780/6eebfd34-b6b5-4770-8c21-bc6172b43443)

**Comment by vbgfbft** [comment]
how u solve it? I have same question, pls help me bro
