### ISSUE TITLE
ImportError: cannot import name 'AutoProcessor' from partially initialized module 'transformers' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by mozgbrasil** [suno-ai/bark#544]
Hello my friends, how are you, I'm trying to run the project example but an error is being returned, can you help me, thank you

```
marcio@marcio-Inspiron-5548:~/dados/git-clones/pessoal/gnz-python/bark$ python examples/transformers.py
Traceback (most recent call last):
  File "/home/marcio/dados/git-clones/pessoal/gnz-python/bark/examples/transformers.py", line 1, in <module>
    from transformers import AutoProcessor, BarkModel
  File "/home/marcio/dados/git-clones/pessoal/gnz-python/bark/examples/transformers.py", line 1, in <module>
    from transformers import AutoProcessor, BarkModel
ImportError: cannot import name 'AutoProcessor' from partially initialized module 'transformers' (most likely due to a circular import) (/home/marcio/dados/git-clones/pessoal/gnz-python/bark/examples/transformers.py)
```

![Captura de tela de 2024-03-26 20-04-37](https://github.com/suno-ai/bark/assets/17202780/ffd21b21-f847-4df8-b58d-159799e063ff)
![Captura de tela de 2024-03-26 20-04-55](https://github.com/suno-ai/bark/assets/17202780/81a9f0cc-e357-4b6e-8638-8ef1ecf55607)

**Comment by maarco** [comment]
change the name of your py file.
