### ISSUE TITLE
Issue using history_prompt

### ISSUE THREAD

**Issue by Yokopops** [suno-ai/bark#557]
I'm getting an issue when trying to generate audio with this code:

from bark import SAMPLE_RATE, generate_audio, preload_models
from scipy.io.wavfile import write as write_wav
import sounddevice as sd

preload_models()

prompt = "Hello, my name is Suno. And, uh — and I like pizza. [laughs] But I also have other interests such as playing tic tac toe."

history_prompt = "P:/AI-Audio/bark/bark/bark/assets/prompts/v2/en_speaker_9.npz"

audio_array = generate_audio(prompt, history_prompt=history_prompt)
# Play audio
print("Playing audio...")
sd.play(audio_array, SAMPLE_RATE)
sd.wait()
print("Audio playback complete.")

If I use no history prompt I get no issue and it generates and plays fine, however when adding the prompt it errors out with:

Traceback (most recent call last):
  File "p:\AI-Audio\bark\Barktest.py", line 11, in <module>
    audio_array = generate_audio(prompt, history_prompt=history_prompt)
  File "C:\Users\Yoko\AppData\Local\Programs\Python\Python310\lib\site-packages\bark\api.py", line 77, in generate_audio
    x_semantic = text_to_semantic(text, history_prompt=history_prompt, temp=text_temp)
  File "C:\Users\Yoko\AppData\Local\Programs\Python\Python310\lib\site-packages\bark\api.py", line 23, in text_to_semantic
    x_semantic = generate_text_semantic(
  File "C:\Users\Yoko\AppData\Local\Programs\Python\Python310\lib\site-packages\bark\generation.py", line 351, in generate_text_semantic
    assert (history_prompt in ALLOWED_PROMPTS)
AssertionError

I am still new to coding and python so go easy on me if I'm overlooking something. Thanks!

**Comment by JonathanFly** [comment]
It is interpreting the way you called that as the name of a default Bark voice instead. Or maybe it can't find your history prompt .npz file. But either way it's basically just not finding the voice. Try using a relative path, or if it's a default voice 'en_speaker_9' by itself. Or use no voice just to test that it works.
