### ISSUE TITLE
python bark_webui.py not working

### ISSUE THREAD

**Issue by Bkura1** [suno-ai/bark#573]
When I run python bark_webui.py (using directml), I get this error:

Traceback (most recent call last):
  File "C:\Users\M\bark\bark_webui.py", line 1339, in <module>
    audio_prompt_input = gr.Audio(
  File "C:\Users\M\miniconda3\envs\pydml_torch2\lib\site-packages\gradio\component_meta.py", line 160, in wrapper
    return fn(self, **kwargs)
TypeError: Audio.__init__() got an unexpected keyword argument 'info'

I tried reinstalling gradio and messing around with stuff there, but nothing seemed to change. There are two things that might be causing it, but are unlikely. I'll mention them just in case. First, my ffmpeg is version 7.0 instead of 6.0, and I'm using Python 3.10.0 instead of 3.10.6.

**Comment by JonathanFly** [comment]
That's actually not an error in Suno's Bark, but in my Bark fork: https://github.com/JonathanFly/bark may not be working with recent Gradio updates. If you find me in the Suno Discord (Jonathan Fly) you can DM me and maybe it's an easy fix though. 

I might setup a mini Discord just to hold Bark DM questions, even though there aren't tons of them, they are very repetitive and there isn't a Bark channel on the Suno server anymore so people can't find old answers.

**Comment by Bkura1** [comment]
> That's actually not an error in Suno's Bark, but in my Bark fork: https://github.com/JonathanFly/bark may not be working with recent Gradio updates. If you find me in the Suno Discord (Jonathan Fly) you can DM me and maybe it's an easy fix though.
> 
> I might setup a mini Discord just to hold Bark DM questions, even though there aren't tons of them, they are very repetitive and there isn't a Bark channel on the Suno server anymore so people can't find old answers.

Thanks. I didn't post it at your fork since it didn't look like there had been any activity since like January.
