### ISSUE TITLE
pip install . does not work

### ISSUE THREAD

**Issue by mateomodar** [suno-ai/bark#584]
When i try to pip install . it gives me this error: 

Processing c:\users\mateo\onedrive\documents\bark\bark
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      configuration error: `project.optional-dependencies.dev[0]` must be string
      DESCRIPTION:
          Project dependency specification according to PEP 508

      GIVEN VALUE:
          {
              "file": "requirements-dev-pip.txt"
          }

      OFFENDING RULE: 'type'

      DEFINITION:
          {
              "$id": "#/definitions/dependency",
              "title": "Dependency",
              "type": "string",
              "format": "pep508"
          }

      For more details about `format` see
      https://validate-pyproject.readthedocs.io/en/latest/api/validate_pyproject.formats.html

      Traceback (most recent call last):
        File "C:\Users\mateo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\mateo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mateo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mateo\AppData\Local\Temp\pip-build-env-ec96wz7n\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mateo\AppData\Local\Temp\pip-build-env-ec96wz7n\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\mateo\AppData\Local\Temp\pip-build-env-ec96wz7n\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
        File "C:\Users\mateo\AppData\Local\Temp\pip-build-env-ec96wz7n\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mateo\AppData\Local\Temp\pip-build-env-ec96wz7n\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 158, in setup
          dist.parse_config_files()
        File "C:\Users\mateo\AppData\Local\Temp\pip-build-env-ec96wz7n\overlay\Lib\site-packages\setuptools\dist.py", line 632, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "C:\Users\mateo\AppData\Local\Temp\pip-build-env-ec96wz7n\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 70, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mateo\AppData\Local\Temp\pip-build-env-ec96wz7n\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 135, in read_configuration
          validate(subset, filepath)
        File "C:\Users\mateo\AppData\Local\Temp\pip-build-env-ec96wz7n\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 59, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project.optional-dependencies.dev[0]`.
      configuration error: `project.optional-dependencies.dev[0]` must be string
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by vbgfbft** [comment]
me too , u solve it?
