### ISSUE TITLE
Support for AMD GPUs? 

### ISSUE THREAD

**Issue by brennschlus** [suno-ai/bark#59]
Hi, thank you for creating this amazing project. I wonder if it is possible to run it on AMD GPUs using the ROCm version of PyTorch, like Stable Diffusion does. I would really appreciate your answer. Thanks again

**Comment by wsippel** [comment]
Works just fine for me, on a 7900XTX running ROCm 5.5-rc4 and PyTorch 2.0. So yes, it's possible.

**Comment by brennschlus** [comment]
> Works just fine for me, on a 7900XTX running ROCm 5.5-rc4 and PyTorch 2.0. So yes, it's possible.

Thanks for reply, I will investigate why I getting error "UserWarning: Can't initialize NVML warnings.warn("Can't initialize NVML")" But in fact it did working on my GPU, I can confirm with rocm-smi

**Comment by tankdnb** [comment]
> Works just fine for me, on a 7900XTX running ROCm 5.5-rc4 and PyTorch 2.0. So yes, it's possible.

u rich as faak

**Comment by Neoony** [comment]
> 

Care to explain how?
Is that on windows?

Also with 7900XTX

**Comment by wsippel** [comment]
@Neoony you also need to compile Torch yourself for now, as there are no binaries for ROCm 5.5 yet. But on the plus side, ROCm 5.5 has actually been released a few days ago, so at least you don't have to track down release candidates and mess with Docker anymore.

**Comment by Milor123** [comment]
Can someone help, i want use it in **windows** with my rx6700 using **DirectML** but i am not sure about of how do it. Please help !

**Comment by ZhenyaPav** [comment]
> Works just fine for me, on a 7900XTX running ROCm 5.5-rc4 and PyTorch 2.0. So yes, it's possible.

Does it work out of the box? I am using a docker image with ROCm 5.5 and Pytorch, same one that works for SD and text-generation-webui, but here I get an error:

```Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/root/venv/lib/python3.10/site-packages/bark/__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform, save_as_prompt
  File "/root/venv/lib/python3.10/site-packages/bark/api.py", line 5, in <module>
    from .generation import codec_decode, generate_coarse, generate_fine, generate_text_semantic
  File "/root/venv/lib/python3.10/site-packages/bark/generation.py", line 6, in <module>
    from encodec import EncodecModel
  File "/root/venv/lib/python3.10/site-packages/encodec/__init__.py", line 12, in <module>
    from .model import EncodecModel
  File "/root/venv/lib/python3.10/site-packages/encodec/model.py", line 19, in <module>
    from .utils import _check_checksum, _linear_overlap_add, _get_checkpoint_url
  File "/root/venv/lib/python3.10/site-packages/encodec/utils.py", line 14, in <module>
    import torchaudio
  File "/root/venv/lib/python3.10/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/root/venv/lib/python3.10/site-packages/torchaudio/_extension/__init__.py", line 43, in <module>
    _load_lib("libtorchaudio")
  File "/root/venv/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "/root/venv/lib/python3.10/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda.so: cannot open shared object file: No such file or directory
```

**Comment by neonarc4** [comment]
@Neoony  but how can i do that is their guide link ?

**Comment by Neoony** [comment]
> @Neoony but how can i do that is their guide link ?

I never managed to get it working
I even forgot where I ended up, but I know at some point I was getting tons of errors with something and wanted to come back to it later, but never did yet
