### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'Tensor'

### ISSUE THREAD

**Issue by jiangjie81** [suno-ai/bark#64]
Traceback (most recent call last):
  File "D:\GitHub\bark\usage.py", line 17, in <module>
    audio_array = generate_audio(text_prompt)
  File "D:\GitHub\bark\bark\api.py", line 113, in generate_audio
    out = semantic_to_waveform(
  File "D:\GitHub\bark\bark\api.py", line 66, in semantic_to_waveform
    audio_arr = codec_decode(fine_tokens)
  File "D:\GitHub\bark\bark\generation.py", line 789, in codec_decode
    emb = model.quantizer.decode(arr)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\encodec-0.1.1-py3.10.egg\encodec\quantization\vq.py", line 112, in decode
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\encodec-0.1.1-py3.10.egg\encodec\quantization\core_vq.py", line 361, in decode
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\encodec-0.1.1-py3.10.egg\encodec\quantization\core_vq.py", line 290, in decode
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\einops\einops.py", line 483, in rearrange
    return reduce(cast(Tensor, tensor), pattern, reduction='rearrange', **axes_lengths)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\einops\einops.py", line 412, in reduce
    return _apply_recipe(recipe, tensor, reduction_type=reduction)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\einops\einops.py", line 233, in _apply_recipe
    backend = get_backend(tensor)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\einops\_backends.py", line 49, in get_backend
    if backend.is_appropriate_type(tensor):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\einops\_backends.py", line 499, in is_appropriate_type
    return isinstance(tensor, (self.tf.Tensor, self.tf.Variable))
AttributeError: module 'tensorflow' has no attribute 'Tensor'
PS D:\GitHub\bark>
------------------------------------
report above error, during first usage. how to solve?

**Comment by gkucsko** [comment]
not sure why you have tensorflow involved in einops here. are you on windows? try looking at einops install or maybe there is something in the encodec repo?

**Comment by Aayush-Goel-04** [comment]
This error may be caused by a version mismatch between the "tensorflow" module and the code that is importing it.

To troubleshoot this error, you could try updating the "tensorflow" module to the latest version or downgrading to a compatible version with the code. 
Additionally, you could check the code to make sure that the "tensorflow" module is imported correctly and that the "Tensor" attribute is being used appropriately.

**Comment by jiangjie81** [comment]
> windows

yes, i run bark on win10. and i updated einops and encodec. let me try to upgrade or modify tensorflow version.

**Comment by gkucsko** [comment]
tensorflow shouldn't be involved as far as i know, even on windows...

**Comment by gkucsko** [comment]
there is also another windows thread.
mind consolidating into there? https://github.com/suno-ai/bark/issues/26
